CREATE TABLE User (
	UserID INT NOT NULL PRIMARY KEY,
	Username NVARCHAR2(20) NOT NULL,
	Password NVARCHAR2(20) NOT NULL,
	Salt NVARCHAR2(200) NOT NULL,
	eMail NVARCHAR2(200) NULL,
	Role INT NOT NULL,
	SignDate DATE NOT NULL,
	Active Bit NOT NULL,
	UserIMG NVARCHAR2(200) NOT NULL,
	Level INT NOT NULL,
	CurrentXP INT NOT NULL 
);

CREATE TABLE PlayerLocation (
  UserID INT NOT NULL PRIMARY KEY,
  X INT NOT NULL,
  Y INT NOT NULL,
  CONSTRAINT Player_Source
    FOREIGN KEY (UserID)
    REFERENCES User(UserID)
    ON DELETE CASCADE
);

CREATE TABLE Equipment (
  EID INT NOT NULL PRIMARY KEY,
  Name NVARCHAR2(200) NOT NULL,
  EqIMG NVARCHAR2(200) NOT NULL
);

CREATE TABLE Resources (
  RID INT NOT NULL PRIMARY KEY,
  Name NVARCHAR2(200) NOT NULL,
  ResIMG NVARCHAR2(200) NOT NULL
);

CREATE TABLE CharEquipment (
  UserID INT NOT NULL,
  EID INT NOT NULL,
  CONSTRAINT Player_Source
    FOREIGN KEY (UserID)
    REFERENCES User(UserID)
    ON DELETE CASCADE,
  CONSTRAINT Equipment_source
    FOREIGN KEY (EID)
    REFERENCES Equipment(EID)
    ON DELETE CASCADE,
  PRIMARY KEY (UserID,EID)
);

CREATE TABLE CharInv (
  UserID INT NOT NULL,
  RID INT NOT NULL,
  Amount INT NOT NULL,
  CONSTRAINT Player_Source
    FOREIGN KEY (UserID)
    REFERENCES User(UserID)
    ON DELETE CASCADE,
  CONSTRAINT Equipment_source
    FOREIGN KEY (RID)
    REFERENCES Resources(RID)
    ON DELETE CASCADE,
  PRIMARY KEY (UserID,RID)  
);

CREATE TABLE MonsterTypes (
  TypeID INT NOT NULL PRIMARY KEY,
  MonsterIMG NVARCHAR2(200) NOT NULL
);

CREATE TABLE ActiveMonster (
  PKID INT NOT NULL PRIMARY KEY,
  TypeID INT NOT NULL,
  MaxHP INT NOT NULL,
  X INT NOT NULL,
  Y INT NOT NULL,
  CurrentHP INT NOT NULL,
  Hunger INT NOT NULL,
  CONSTRAINT MonsterType_Source
    FOREIGN KEY (TYPEID)
    REFERENCES MonsterTypes(TypeID)
    ON DELETE CASCADE
);

CREATE TABLE SurfaceType (
  SID INT NOT NULL PRIMARY KEY,
  Name NVARCHAR2(200) NOT NULL,
  SurfaceIMG NVARCHAR2(200) NOT NULL
);

CREATE TABLE TileSurface (
  X INT NOT NULL,
  Y INT NOT NULL,
  SID INT NOT NULL,
  CONSTRAINT Surface_Source
    FOREIGN KEY (SID)
    REFERENCES SurfaceType(SID)
    ON DELETE CASCADE,
  PRIMARY KEY (X,Y)
);

CREATE TABLE TileObject (
  X INT NOT NULL,
  Y INT NOT NULL,
  OID INT NOT NULL,
  CONSTRAINT User_Source
    FOREIGN KEY (OID)
    REFERENCES User(UserID)
    ON DELETE CASCADE,
  CONSTRAINT Resource_Source
    FOREIGN KEY (OID)
    REFERENCES Resources(RID)
    ON DELETE CASCADE,
  CONSTRAINT Monster_Source
    FOREIGN KEY (OID)
    REFERENCES ActiveMonster(PKID)
    ON DELETE CASCADE,
  PRIMARY KEY (X,Y)
);