CREATE TABLE IF NOT EXISTS User (
	UserID INT NOT NULL PRIMARY KEY,
	Username VARCHAR(20) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Salt VARCHAR(200) NOT NULL,
	eMail VARCHAR(200) NULL,
	Role INT NOT NULL,
	SignDate DATE NOT NULL,
	Active Bit NOT NULL,
	UserIMG VARCHAR(200) NOT NULL,
	Level INT NOT NULL,
	CurrentXP INT NOT NULL 
);

CREATE TABLE IF NOT EXISTS PlayerLocation (
  UserID INT NOT NULL PRIMARY KEY,
  X INT NOT NULL,
  Y INT NOT NULL,
  CONSTRAINT Player_Source
    FOREIGN KEY (UserID)
    REFERENCES User(UserID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Equipment (
  EID INT NOT NULL PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  EqIMG VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Resources (
  RID INT NOT NULL PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  ResIMG VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS CharEquipment (
  UserID INT NOT NULL,
  EID INT NOT NULL,
  CONSTRAINT Player_SourceEq
    FOREIGN KEY (UserID)
    REFERENCES User(UserID)
    ON DELETE CASCADE,
  CONSTRAINT Equipment_sourceEq
    FOREIGN KEY (EID)
    REFERENCES Equipment(EID)
    ON DELETE CASCADE,
  PRIMARY KEY (UserID,EID)
);

CREATE TABLE IF NOT EXISTS CharInv (
  UserID INT NOT NULL,
  RID INT NOT NULL,
  Amount INT NOT NULL,
  CONSTRAINT Player_SourceInv
    FOREIGN KEY (UserID)
    REFERENCES User(UserID)
    ON DELETE CASCADE,
  CONSTRAINT Equipment_sourceInv
    FOREIGN KEY (RID)
    REFERENCES Resources(RID)
    ON DELETE CASCADE,
  PRIMARY KEY (UserID,RID)  
);

CREATE TABLE IF NOT EXISTS MonsterTypes (
  TypeID INT NOT NULL PRIMARY KEY,
  MonsterIMG VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS ActiveMonster (
  PKID INT NOT NULL PRIMARY KEY,
  TypeID INT NOT NULL,
  MaxHP INT NOT NULL,
  X INT NOT NULL,
  Y INT NOT NULL,
  CurrentHP INT NOT NULL,
  Hunger INT NOT NULL,
  CONSTRAINT MonsterType_Source
    FOREIGN KEY (TYPEID)
    REFERENCES MonsterTypes(TypeID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SurfaceType (
  SID INT NOT NULL PRIMARY KEY,
  Name VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS TileSurface (
  X INT NOT NULL,
  Y INT NOT NULL,
  SID INT NOT NULL,
  CONSTRAINT Surface_Source
    FOREIGN KEY (SID)
    REFERENCES SurfaceType(SID)
    ON DELETE CASCADE,
  PRIMARY KEY (X,Y)
);

CREATE TABLE IF NOT EXISTS TileObject (
  X INT NOT NULL,
  Y INT NOT NULL,
  OID INT NOT NULL,
  CONSTRAINT User_Source
    FOREIGN KEY (OID)
    REFERENCES User(UserID)
    ON DELETE CASCADE,
  CONSTRAINT Resource_Source
    FOREIGN KEY (OID)
    REFERENCES Resources(RID)
    ON DELETE CASCADE,
  CONSTRAINT Monster_Source
    FOREIGN KEY (OID)
    REFERENCES ActiveMonster(PKID)
    ON DELETE CASCADE,
  PRIMARY KEY (X,Y)
);